import { StyleSheet, Dimensions, Platform } from 'react-native';
import { BRAND } from '../../../theme';

const { width } = Dimensions.get('window');
const isSmallDevice = width < 375;
const PAD = width * 0.055;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BRAND.bg },
  scroll: { flex: 1 },
  scrollContent: { paddingTop: Platform.OS === 'ios' ? 4 : 40, paddingBottom: 110 },

  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: PAD,
    paddingBottom: 4,
  },
  title: { fontSize: isSmallDevice ? 26 : 30, fontFamily: 'Nunito_800ExtraBold', color: BRAND.ink },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1.5,
    borderColor: '#F3C9C4',
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  logoutText: { color: BRAND.danger, fontFamily: 'Nunito_700Bold', fontSize: 14 },
  subtitle: {
    fontSize: 14.5,
    fontFamily: 'Nunito_400Regular',
    color: BRAND.inkSoft,
    paddingHorizontal: PAD,
    marginTop: 2,
    marginBottom: 16,
  },

  // ---- Card de perfil ----
  profileCard: {
    backgroundColor: BRAND.card,
    borderRadius: 22,
    marginHorizontal: PAD,
    padding: 20,
    borderWidth: 1,
    borderColor: BRAND.border,
  },
  profileTop: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  avatarWrapper: { position: 'relative' },
  avatarPlaceholder: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: '#E7EEFB',
    borderWidth: 3,
    borderColor: BRAND.blue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarInitial: { fontSize: 34, fontFamily: 'Nunito_800ExtraBold', color: BRAND.blue },
  editBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: BRAND.blue,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: BRAND.card,
  },
  userName: { fontSize: 22, fontFamily: 'Nunito_800ExtraBold', color: BRAND.ink },
  userEmail: { fontSize: 13.5, fontFamily: 'Nunito_400Regular', color: BRAND.inkSoft, marginTop: 1 },
  verifiedRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 6 },
  verifiedText: { fontSize: 13, fontFamily: 'Nunito_700Bold', color: BRAND.success },
  editProfileBtn: {
    backgroundColor: BRAND.blue,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  editProfileText: { color: '#fff', fontFamily: 'Nunito_700Bold', fontSize: 15 },
  progressRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 16 },
  progressLabel: { fontSize: 13, fontFamily: 'Nunito_600SemiBold', color: BRAND.inkSoft },
  progressBarBg: { flex: 1, height: 7, borderRadius: 99, backgroundColor: '#E4E7EC' },
  progressBarFill: { height: '100%', borderRadius: 99, backgroundColor: BRAND.blue },
  progressLink: { fontSize: 13.5, fontFamily: 'Nunito_700Bold', color: BRAND.blue },

  // ---- Impacto (stats) ----
  sectionLabel: {
    fontSize: 19,
    fontFamily: 'Nunito_800ExtraBold',
    color: BRAND.ink,
    marginHorizontal: PAD,
    marginTop: 24,
    marginBottom: 12,
  },
  statsRow: {
    flexDirection: 'row',
    backgroundColor: BRAND.card,
    borderRadius: 20,
    marginHorizontal: PAD,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: BRAND.border,
  },
  statBox: { flex: 1, alignItems: 'center' },
  statDivider: { borderLeftWidth: 1, borderRightWidth: 1, borderColor: BRAND.border },
  statNumber: { fontSize: 26, fontFamily: 'Nunito_800ExtraBold', color: BRAND.blue },
  statLabel: { fontSize: 12.5, fontFamily: 'Nunito_600SemiBold', color: BRAND.inkSoft, marginTop: 2 },

  // ---- Menu ----
  menuSection: {
    backgroundColor: BRAND.card,
    borderRadius: 20,
    marginHorizontal: PAD,
    borderWidth: 1,
    borderColor: BRAND.border,
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: BRAND.border,
  },
  menuItemLast: { borderBottomWidth: 0 },
  menuItemLeft: { flexDirection: 'row', alignItems: 'center', gap: 14, flex: 1 },
  iconContainer: { width: 40, height: 40, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  menuItemTitle: { fontSize: 15, fontFamily: 'Nunito_700Bold', color: BRAND.ink },
  menuItemSub: { fontSize: 12.5, fontFamily: 'Nunito_400Regular', color: BRAND.inkSoft, marginTop: 1 },
  menuBadge: {
    backgroundColor: '#E3F3E9',
    borderRadius: 20,
    paddingVertical: 3,
    paddingHorizontal: 10,
  },
  menuBadgeText: { fontSize: 12, fontFamily: 'Nunito_700Bold', color: BRAND.success },

  // ---- Ajuda ----
  helpCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#E7EEFB',
    borderRadius: 18,
    marginHorizontal: PAD,
    marginTop: 20,
    padding: 16,
  },
  helpIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: BRAND.card,
    justifyContent: 'center',
    alignItems: 'center',
  },
  helpTitle: { fontSize: 15, fontFamily: 'Nunito_800ExtraBold', color: BRAND.ink },
  helpText: { fontSize: 12.5, fontFamily: 'Nunito_400Regular', color: BRAND.inkSoft, marginTop: 1 },
  helpBtn: {
    borderWidth: 1.5,
    borderColor: BRAND.blue,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  helpBtnText: { color: BRAND.blue, fontFamily: 'Nunito_700Bold', fontSize: 12.5 },
});
