import { StyleSheet, Dimensions, Platform } from 'react-native';
import { BRAND } from '../../../theme';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BRAND.bg },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: width * 0.05,
    paddingTop: Platform.OS === 'ios' ? 6 : height * 0.015,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: BRAND.blue,
    backgroundColor: BRAND.card,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  logoText: { fontSize: 28, fontFamily: 'Nunito_800ExtraBold', color: BRAND.blue },
  stepLabel: { fontSize: 14, fontFamily: 'Nunito_700Bold', color: BRAND.ink },
  illustration: {
    alignSelf: 'center',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#E7EEFB',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.03,
    marginBottom: 8,
  },
  card: {
    backgroundColor: BRAND.card,
    borderRadius: 24,
    marginHorizontal: width * 0.05,
    marginTop: 14,
    padding: 24,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  title: { fontSize: 28, fontFamily: 'Nunito_800ExtraBold', color: BRAND.ink },
  description: {
    fontSize: 14.5,
    fontFamily: 'Nunito_400Regular',
    color: BRAND.inkSoft,
    marginTop: 10,
    lineHeight: 21,
  },
  label: {
    fontSize: 14,
    fontFamily: 'Nunito_700Bold',
    color: BRAND.ink,
    marginTop: 18,
    marginBottom: 6,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: BRAND.card,
    borderRadius: 14,
    height: 58,
    borderWidth: 1,
    borderColor: '#D7DBE2',
    overflow: 'hidden',
  },
  input: {
    flex: 1,
    height: '100%',
    paddingHorizontal: 12,
    fontSize: 15,
    fontFamily: 'Nunito_400Regular',
    color: BRAND.ink,
    ...Platform.select({ web: { outlineStyle: 'none' } }),
  },
  eyeButton: { paddingHorizontal: 14, height: '100%', justifyContent: 'center' },
  strengthRow: { flexDirection: 'row', gap: 6, marginTop: 12 },
  strengthBar: { flex: 1, height: 6, borderRadius: 99, backgroundColor: '#E4E7EC' },
  strengthLabel: { textAlign: 'right', fontSize: 12.5, fontFamily: 'Nunito_700Bold', marginTop: 6 },
  button: {
    backgroundColor: BRAND.blue,
    height: 58,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
  },
  buttonText: { color: '#FFFFFF', fontSize: 17, fontFamily: 'Nunito_700Bold' },
  footer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 24, paddingBottom: 24 },
  footerText: { fontSize: 14, fontFamily: 'Nunito_400Regular', color: BRAND.inkSoft },
  supportLink: { fontSize: 14, fontFamily: 'Nunito_700Bold', color: BRAND.blue },
  popupContainer: { position: 'absolute', bottom: 50, left: 20, right: 20, zIndex: 999 },
  popupContent: {
    backgroundColor: BRAND.card,
    padding: 15,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    borderLeftWidth: 5,
  },
  popupText: { marginLeft: 10, color: BRAND.ink, fontSize: 14, flex: 1 },
});

export default styles;
