import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');
const isSmallDevice = screenWidth < 375;

// Cores fofas e acolhedoras para o universo Pet
export const colors = {
  bgWarm: '#FFFBF7',        // Creme suave de fundo
  peachLight: '#FFEFEB',    // Pêssego pastel bem clarinho
  peach: '#FF8E72',         // Coral/Pêssego principal (botões e destaques)
  pastelBlue: '#A5C9FF',    // Azul bebê
  pastelPurple: '#D8B4F8',  // Lavanda fofo
  pastelGreen: '#A2E3C4',   // Verde menta suave
  textDark: '#4A3E3D',      // Marrom cacau para um contraste suave e aconchegante
  textMuted: '#8C7E7C',     // Cinza caloroso para descrições secundárias
  white: '#FFFFFF',
  gold: '#FFD166',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bgWarm,
  },
  scroll: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: screenWidth * 0.06,
    paddingTop: Platform.OS === 'ios' ? 20 : 50,
    paddingBottom: 10,
  },
  logo: {
    fontSize: isSmallDevice ? 26 : 28,
    fontWeight: 'bold',
    color: colors.peach,
    letterSpacing: -0.5,
  },
  headerRight: {
    flexDirection: 'row',
    gap: 12,
  },
  greetingSection: {
    paddingHorizontal: screenWidth * 0.06,
    marginVertical: 12,
  },
  greeting: {
    fontSize: isSmallDevice ? 20 : 24,
    fontWeight: 'bold',
    color: colors.textDark,
    marginBottom: 12,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 18,
    paddingHorizontal: 15,
    height: 48,
    borderWidth: 1.5,
    borderColor: '#F2EBE5',
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    color: colors.textDark,
  },
  toggleContainer: {
    paddingHorizontal: screenWidth * 0.06,
    marginBottom: 10,
  },
  toggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  toggleText: {
    color: colors.peach,
    fontWeight: '600',
    fontSize: 14,
  },
  smartInsightsCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    marginHorizontal: screenWidth * 0.06,
    marginBottom: 20,
    elevation: 3,
    shadowColor: colors.textDark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    alignItems: 'center',
  },
  insightIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.peachLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textDark,
    marginBottom: 12,
  },
  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 5,
  },
  metric: {
    alignItems: 'center',
  },
  metricNumber: {
    fontSize: 26,
    fontWeight: 'bold',
    color: colors.peach,
  },
  metricLabel: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  ctaCard: {
    backgroundColor: colors.peach,
    borderRadius: 24,
    padding: 22,
    marginHorizontal: screenWidth * 0.06,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ctaTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.white,
  },
  ctaText: {
    fontSize: 13,
    color: colors.white,
    opacity: 0.9,
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textDark,
    marginHorizontal: screenWidth * 0.06,
    marginBottom: 12,
  },
  matchCard: {
    height: screenHeight * 0.32,
    marginHorizontal: screenWidth * 0.06,
    borderRadius: 24,
    overflow: 'hidden',
    marginBottom: 25,
    elevation: 4,
    shadowColor: colors.textDark,
    shadowOpacity: 0.08,
    shadowRadius: 10,
  },
  matchImage: {
    width: '100%',
    height: '100%',
  },
  imageGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '50%',
  },
  matchInfoOverlay: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  matchNameWhite: {
    color: colors.white,
    fontSize: 20,
    fontWeight: 'bold',
  },
  matchBreedWhite: {
    color: colors.white,
    opacity: 0.9,
    fontSize: 13,
    marginTop: 2,
  },
  matchPercentBadge: {
    backgroundColor: colors.white,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
  },
  matchPercentText: {
    color: colors.peach,
    fontWeight: '700',
    fontSize: 12,
  },
  progressCard: {
    backgroundColor: colors.white,
    padding: 18,
    borderRadius: 22,
    marginHorizontal: screenWidth * 0.06,
    marginBottom: 25,
    borderWidth: 1.5,
    borderColor: '#FAF1ED',
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  progressLabel: {
    fontWeight: '700',
    color: colors.textDark,
  },
  progressValue: {
    color: colors.peach,
    fontWeight: 'bold',
  },
  progressBarBg: {
    height: 8,
    backgroundColor: colors.peachLight,
    borderRadius: 4,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: colors.peach,
    borderRadius: 4,
  },
  suggestionsList: {
    paddingLeft: screenWidth * 0.06,
    paddingBottom: 20,
  },
  petSuggestionCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 10,
    marginRight: 15,
    width: screenWidth * 0.38,
    elevation: 2,
    shadowColor: colors.textDark,
    shadowOpacity: 0.03,
    shadowRadius: 5,
  },
  petSuggestionImage: {
    width: '100%',
    height: screenWidth * 0.33,
    borderRadius: 16,
    marginBottom: 8,
  },
  petName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.textDark,
  },
  petBreed: {
    fontSize: 12,
    color: colors.textMuted,
  },

  // --- ESTILOS DO TUTORIAL / SLIDES ---
  slideContainer: {
    width: screenWidth,
    height: screenHeight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bgCircle: {
    position: 'absolute',
    borderRadius: 999,
  },
  slideContent: {
    width: '100%',
    paddingHorizontal: screenWidth * 0.08,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -screenHeight * 0.08,
  },
  slideIconContainer: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: colors.white,
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
    elevation: 4,
    shadowColor: colors.textDark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    position: 'relative',
  },
  miniPawBadge: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    fontSize: 26,
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 4,
    overflow: 'hidden',
  },
  slideTitle: {
    fontSize: isSmallDevice ? 22 : 25,
    fontWeight: 'bold',
    color: colors.textDark,
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 30,
  },
  slideDescription: {
    fontSize: isSmallDevice ? 14 : 15,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 8,
  },
  skipButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 55 : 45,
    right: 25,
    zIndex: 999, // Alto valor para garantir clique sobre o modal
    paddingVertical: 6,
    paddingHorizontal: 15,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderWidth: 1,
    borderColor: '#F2EBE5',
  },
  skipButtonText: {
    color: colors.textDark,
    fontWeight: '700',
    fontSize: 12,
  },
  slideFooter: {
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 45 : 30,
    left: 0,
    right: 0,
    paddingHorizontal: screenWidth * 0.08,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 999,
  },
  paginationDotsContainer: {
    width: 80, 
    height: 30,
    justifyContent: 'center',
    position: 'relative',
  },
  passiveDotsRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  dotInactive: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(74, 62, 61, 0.15)',
  },
  dotActiveAnimated: {
    position: 'absolute',
    left: -3,
    top: 3,
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  slideActionNext: {
    backgroundColor: colors.peach,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    elevation: 3,
    shadowColor: colors.peach,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  slideActionNextText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 14,
  },
});