import { StyleSheet, Dimensions, Platform } from 'react-native';
import { BRAND } from '../../../theme';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');
const isSmallDevice = screenWidth < 375;
const PAD = screenWidth * 0.055;

// Paleta da Home alinhada à marca. Algumas chaves legadas (pastel*, gold)
// permanecem porque o modal de tutorial ainda as referencia.
export const colors = {
  bgWarm: BRAND.bg,
  peachLight: '#E7EEFB',
  peach: BRAND.blue,           // acento principal = azul da marca
  pastelBlue: '#A5C9FF',
  pastelPurple: '#D8B4F8',
  pastelGreen: '#A2E3C4',
  textDark: BRAND.ink,
  textMuted: BRAND.inkSoft,
  white: BRAND.card,
  gold: BRAND.honey,
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bgWarm },
  scroll: { flex: 1 },

  // ---- Cabeçalho ----
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: PAD,
    paddingTop: Platform.OS === 'ios' ? 12 : 44,
    paddingBottom: 6,
  },
  logoRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  logo: { fontSize: isSmallDevice ? 26 : 28, fontFamily: 'Nunito_800ExtraBold', color: colors.peach },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  bellWrap: { position: 'relative' },
  bellDot: {
    position: 'absolute',
    top: -1,
    right: -1,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: BRAND.blue,
    borderWidth: 1.5,
    borderColor: colors.bgWarm,
  },
  avatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.peachLight },

  locationPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    marginHorizontal: PAD,
    marginTop: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: BRAND.border,
    backgroundColor: colors.white,
  },
  locationText: { fontSize: 13.5, fontFamily: 'Nunito_700Bold', color: colors.textDark },

  greetingSection: { paddingHorizontal: PAD, marginTop: 10 },
  greeting: { fontSize: isSmallDevice ? 26 : 30, fontFamily: 'Nunito_800ExtraBold', color: colors.textDark },
  greetingSub: { fontSize: 14.5, fontFamily: 'Nunito_400Regular', color: colors.textMuted, marginTop: 2 },

  // ---- Busca ----
  searchRow: { flexDirection: 'row', gap: 10, paddingHorizontal: PAD, marginTop: 16 },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingHorizontal: 15,
    height: 52,
    borderWidth: 1,
    borderColor: BRAND.border,
  },
  searchInput: { flex: 1, marginLeft: 10, fontSize: 15, fontFamily: 'Nunito_400Regular', color: colors.textDark },
  filterBtn: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: BRAND.blue,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // ---- Ações rápidas ----
  quickRow: { flexDirection: 'row', gap: 10, paddingHorizontal: PAD, marginTop: 16 },
  quickCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: BRAND.border,
  },
  quickCardActive: { backgroundColor: colors.peachLight, borderColor: BRAND.blue },
  quickLabel: { fontSize: 12.5, fontFamily: 'Nunito_700Bold', color: colors.textDark },

  // ---- Banner de progresso do perfil (card navy) ----
  profileBanner: {
    backgroundColor: BRAND.navy,
    borderRadius: 20,
    marginHorizontal: PAD,
    marginTop: 18,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  profileBannerIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileBannerText: { color: '#fff', fontFamily: 'Nunito_700Bold', fontSize: 14.5 },
  profileBarBg: { height: 7, borderRadius: 99, backgroundColor: 'rgba(255,255,255,0.2)', marginTop: 8 },
  profileBarFill: { height: '100%', borderRadius: 99, backgroundColor: BRAND.blue },
  profileContinue: { color: '#fff', fontFamily: 'Nunito_700Bold', fontSize: 13.5 },

  // ---- Seções ----
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: PAD,
    marginTop: 24,
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 21, fontFamily: 'Nunito_800ExtraBold', color: colors.textDark },
  sectionLink: { fontSize: 14, fontFamily: 'Nunito_700Bold', color: BRAND.blue },

  // ---- Card do melhor match ----
  matchCard: {
    marginHorizontal: PAD,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: BRAND.border,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
  },
  matchImageWrap: { height: screenHeight * 0.28, position: 'relative' },
  matchImage: { width: '100%', height: '100%' },
  compatBadge: {
    position: 'absolute',
    top: 14,
    left: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.white,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 14,
  },
  compatValue: { fontSize: 15, fontFamily: 'Nunito_800ExtraBold', color: BRAND.blue },
  compatLabel: { fontSize: 10.5, fontFamily: 'Nunito_600SemiBold', color: colors.textMuted },
  heartBtn: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ongBadge: {
    position: 'absolute',
    bottom: 12,
    left: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.white,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 14,
  },
  ongBadgeText: { fontSize: 12.5, fontFamily: 'Nunito_700Bold', color: colors.textDark },
  matchBody: { padding: 16 },
  matchTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  matchName: { fontSize: 24, fontFamily: 'Nunito_800ExtraBold', color: colors.textDark },
  matchMeta: { fontSize: 13.5, fontFamily: 'Nunito_400Regular', color: colors.textMuted, marginTop: 2 },
  matchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: BRAND.blue,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
  },
  matchBtnText: { color: '#fff', fontFamily: 'Nunito_700Bold', fontSize: 14 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderColor: BRAND.border,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  tagText: { fontSize: 12.5, fontFamily: 'Nunito_600SemiBold', color: colors.textDark },

  // ---- Card de campanha ----
  campaignCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: colors.peachLight,
    borderRadius: 20,
    marginHorizontal: PAD,
    marginTop: 20,
    padding: 16,
  },
  campaignIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: BRAND.blue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  campaignTitle: { fontSize: 16, fontFamily: 'Nunito_800ExtraBold', color: colors.textDark },
  campaignText: { fontSize: 12.5, fontFamily: 'Nunito_400Regular', color: colors.textMuted, marginTop: 2 },
  campaignBarBg: { height: 7, borderRadius: 99, backgroundColor: '#D5E1F7', marginTop: 8 },
  campaignBarFill: { height: '100%', borderRadius: 99, backgroundColor: BRAND.blue },
  campaignBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    borderWidth: 1.5,
    borderColor: BRAND.blue,
    borderRadius: 20,
    paddingVertical: 7,
    paddingHorizontal: 16,
  },
  campaignBtnText: { color: BRAND.blue, fontFamily: 'Nunito_700Bold', fontSize: 13 },

  // ================= TUTORIAL / SLIDES (preservado) =================
  slideContainer: { width: screenWidth, height: screenHeight, justifyContent: 'center', alignItems: 'center' },
  bgCircle: { position: 'absolute', borderRadius: 999 },
  slideContent: {
    width: '100%',
    paddingHorizontal: screenWidth * 0.08,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -screenHeight * 0.08,
  },
  slideIconContainer: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: colors.white,
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
    elevation: 4,
    shadowColor: colors.textDark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
  },
  slideTitle: {
    fontSize: isSmallDevice ? 22 : 25,
    fontWeight: 'bold',
    color: colors.textDark,
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 30,
  },
  slideDescription: {
    fontSize: isSmallDevice ? 14 : 15,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 8,
  },
  skipButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 55 : 45,
    right: 25,
    zIndex: 999,
    paddingVertical: 6,
    paddingHorizontal: 15,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderWidth: 1,
    borderColor: BRAND.border,
  },
  skipButtonText: { color: colors.textDark, fontWeight: '700', fontSize: 12 },
  slideFooter: {
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 45 : 30,
    left: 0,
    right: 0,
    paddingHorizontal: screenWidth * 0.08,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 999,
  },
  paginationDotsContainer: { width: 80, height: 30, justifyContent: 'center', position: 'relative' },
  passiveDotsRow: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  dotInactive: { width: 10, height: 10, borderRadius: 5, backgroundColor: 'rgba(12,35,64,0.15)' },
  dotActiveAnimated: {
    position: 'absolute',
    left: -3,
    top: 3,
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  slideActionNext: {
    backgroundColor: colors.peach,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    elevation: 3,
    shadowColor: colors.peach,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  slideActionNextText: { color: colors.white, fontWeight: 'bold', fontSize: 14 },
});
