import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const colors = {
  navy: '#05082B',
  blue: '#1D5CFF',
  white: '#FFFFFF',
  gray: '#6B7280',
  lightGray: '#F3F4F6',
  green: '#059669',
  ice: '#F8FAFC',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.ice,
  },
  scroll: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: screenWidth * 0.06,
    paddingTop: Platform.OS === 'ios' ? 20 : 50,
    paddingBottom: 10,
  },
  logo: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colors.blue,
    letterSpacing: -1,
  },
  headerRight: {
    flexDirection: 'row',
    gap: 15,
  },
  greetingSection: {
    paddingHorizontal: screenWidth * 0.06,
    marginVertical: 15,
  },
  greeting: {
    fontSize: 26,
    fontWeight: 'bold',
    color: colors.navy,
    marginBottom: 15,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingHorizontal: 15,
    height: 50,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
    color: colors.navy,
  },
  toggleContainer: {
    paddingHorizontal: screenWidth * 0.06,
    marginBottom: 10,
  },
  toggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  toggleText: {
    color: colors.blue,
    fontWeight: '600',
    fontSize: 14,
  },
  smartInsightsCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 20,
    marginHorizontal: screenWidth * 0.06,
    marginBottom: 20,
    elevation: 4,
    shadowColor: colors.navy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.navy,
    marginBottom: 15,
  },
  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  metric: {
    alignItems: 'center',
  },
  metricNumber: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.blue,
  },
  metricLabel: {
    fontSize: 12,
    color: colors.gray,
    marginTop: 2,
  },
  ctaCard: {
    backgroundColor: colors.blue,
    borderRadius: 24,
    padding: 25,
    marginHorizontal: screenWidth * 0.06,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ctaTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.white,
  },
  ctaText: {
    fontSize: 14,
    color: colors.white,
    opacity: 0.8,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.navy,
    marginHorizontal: screenWidth * 0.06,
    marginBottom: 15,
  },
  matchCard: {
    height: screenHeight * 0.35,
    marginHorizontal: screenWidth * 0.06,
    borderRadius: 30,
    overflow: 'hidden',
    marginBottom: 25,
    elevation: 8,
    shadowColor: colors.navy,
    shadowOpacity: 0.2,
    shadowRadius: 15,
  },
  matchImage: {
    width: '100%',
    height: '100%',
  },
  imageGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '60%',
  },
  matchInfoOverlay: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  matchNameWhite: {
    color: colors.white,
    fontSize: 22,
    fontWeight: 'bold',
  },
  matchBreedWhite: {
    color: colors.white,
    opacity: 0.9,
    fontSize: 14,
  },
  matchPercentBadge: {
    backgroundColor: colors.green,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  matchPercentText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 12,
  },
  progressCard: {
    backgroundColor: colors.white,
    padding: 20,
    borderRadius: 24,
    marginHorizontal: screenWidth * 0.06,
    marginBottom: 25,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  progressLabel: {
    fontWeight: '600',
    color: colors.navy,
  },
  progressValue: {
    color: colors.blue,
    fontWeight: 'bold',
  },
  progressBarBg: {
    height: 8,
    backgroundColor: colors.lightGray,
    borderRadius: 4,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: colors.blue,
    borderRadius: 4,
  },
  suggestionsList: {
    paddingLeft: screenWidth * 0.06,
    paddingBottom: 20,
  },
  petSuggestionCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 12,
    marginRight: 15,
    width: 160,
    elevation: 3,
    shadowColor: colors.navy,
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  petSuggestionImage: {
    width: '100%',
    height: 140,
    borderRadius: 15,
    marginBottom: 10,
  },
  petName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.navy,
  },
  petBreed: {
    fontSize: 12,
    color: colors.gray,
  },
  navbar: {
    position: 'absolute',
    bottom: 25,
    left: screenWidth * 0.06,
    right: screenWidth * 0.06,
    height: 70,
    backgroundColor: colors.white,
    borderRadius: 25,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    elevation: 10,
    shadowColor: colors.navy,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
  },
});